### ISSUE TITLE
Test_Results get functions modify state

### ISSUE THREAD

**Issue by TamaMcGlinn** [AdaCore/aunit#6]
I am writing a test reporter that outputs to TRX format for interpretation by a vNext TFS build server. However, it would be nice to also output to the console in the default way that AUnit.Reporter.Text already does, without introducing any duplicate code. The logical thing that came to mind was to make a Combiner reporter, that is a reporter which you can add reporters to, and which simply executes each of those in turn.

Unfortunately, the AUnit.Test_Results package, first of all, doesn't even allow you to get a list of the results. It has it right there as a field of the Result record, but it isn't exposed through a public accessor function.

There is a generic procedure Gen_Extract (that takes a filter function), which I could pass a function returning True for all inputs, but Gen_Extract is private.

Okay, we will work around it by calling Failures, Errors and Successes in turn, which will go through the list 3 times instead of once, but at least it works.

```
   package Test_Vecs is new Ada.Containers.Vectors
       (Element_Type => Test_Result,
        Index_Type => Positive);

   function Get_Results (R : in out Result'Class) return Test_Vecs.Vector is
      All_Results : Test_Vecs.Vector;
      F, E, S : Result_Lists.List;

      procedure Get_Result_List (L : Result_Lists.List) is
         use Result_Lists;
         C : Cursor := First (L);
      begin
         while Has_Element (C) loop
            All_Results.Append (Element (C));
            Next (C);
         end loop;
      end Get_Result_List;

   begin
      Failures (R, F);
      Errors (R, E);
      Successes (R, S);
      Get_Result_List (F);
      Get_Result_List (E);
      Get_Result_List (S);
      return All_Results;
   end Get_Results;
```

If I do this inside my TRX format test reporter, it **empties out the results list**. So that means that whichever reporter runs first gets the results, while the next reporter gets nothing at all. As this comment in the source code indicates, these getter functions delete the results that are returned.

```
   procedure Failures (R : in out Result; F : in out Result_Lists.List);
   --  List of failed routines. This resets the list.
```

So how do we work around this? You may think you could just copy the Result, and pass one copy to the TRX test reporter, the other to the standard text reporter. Nope; Result is not only private, but also limited, prohibiting copying.

It would be possible to do the above Get_Results inside the reporter combiner, and then pass the resulting vector to my own pseudo-reporters, but that means rewriting the standard text reporter to accept the newly defined result vector type. I'd much rather be able to run a standard reporter and not have it change the list of results.

I'd love for any feedback on these three points of improvement before I open my PR:

- Result will have a public function to get all the results
- None of the result accessor functions will remove elements
- Result will not be limited

**Comment by Patschkowski** [comment]
Hi,

I think a better approach for your problem would be to have T-stream so that the results are not processed twice but instead the output is forwarded to 2 output streams.

This requires my latest pull request to be accepted, though: https://github.com/AdaCore/aunit/pull/3

Kind regards,
Felix

**Comment by TamaMcGlinn** [comment]
@Patschkowski That doesn't work for me because the stream to the console should be in a different format than the stream to a .trx file. However, I do like your additions and will use them to set the trx output file; this removes some logic from the trx reporter and makes it more flexible.
